### ISSUE TITLE
Feature Request: Option to show date in relative time

### ISSUE THREAD

**Issue by triplecillas** [royto/logbook-card#71]
First of all thank you for a very useful card.

Would it be possible to add a feature to show date in relative time format?
Examples: today at 13:30, yesterday at 14h, 3 days ago, etc.

Thank you again!

**Comment by ThomDietrich** [comment]
Hey @royto, amazing, thanks for the quick response!

I've tested the new version and everything looks good. Upon further thought I am actually not the biggest fan of this replacing the start and end time.

Let me show my use case:

![image](https://github.com/royto/logbook-card/assets/2870104/94def506-dcb9-4d95-9681-bf3f74ce88ca)

As you can see, I am trying to list events rather than states. For that use case I would love something similar to this:

![image](https://github.com/royto/logbook-card/assets/2870104/6b3acf35-d4dc-425e-ac42-7425d51b6268)

Does that make sense?
